### ISSUE TITLE
Crash when open command in offline

### ISSUE THREAD

**Issue by azizov4singree** [gianasista/tldr-viewer#2]
Steps to reproduce:
1. Open app when connected to network
2. Wait until command list will be loaded
3. Turn off WiFi connection
4. Open any command

**Comment by gianasista** [comment]
Stack trace:

```
12-30 21:05:55.391 12512-12512/de.gianasista.tldr_viewer E/de.gianasista.tldr_viewer.backend.TldrApiClient: Http-Error-Code: 0
                                                                                                            java.io.IOException: UnknownHostException exception: Unable to resolve host "raw.githubusercontent.com": No address associated with hostname
                                                                                                                at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:118)
                                                                                                                at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:68)
                                                                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                                at java.lang.Thread.run(Thread.java:818)
12-30 21:05:55.394 12512-12512/de.gianasista.tldr_viewer D/AndroidRuntime: Shutting down VM
12-30 21:05:55.400 12512-12512/de.gianasista.tldr_viewer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: de.gianasista.tldr_viewer, PID: 12512
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                               at java.io.StringReader.<init>(StringReader.java:47)
                                                                               at android.text.HtmlToSpannedConverter.convert(Html.java:449)
                                                                               at android.text.Html.fromHtml(Html.java:136)
                                                                               at android.text.Html.fromHtml(Html.java:99)
                                                                               at de.gianasista.tldr_viewer.CommandContentActivity.receiveCommandContent(CommandContentActivity.java:133)
                                                                               at de.gianasista.tldr_viewer.backend.TldrApiClient$1.onFailure(TldrApiClient.java:40)
                                                                               at com.loopj.android.http.TextHttpResponseHandler.onFailure(TextHttpResponseHandler.java:104)
                                                                               at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:284)
                                                                               at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:134)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by azizov4singree** [comment]
:+1:
